CREATE TABLE USERS_GRUPO_ENLACE (
  ID INTEGER,
  TYPE VARCHAR(2),
  NAME VARCHAR(30),
  EMAIL  VARCHAR(100),
  PRIMARY KEY(ID)
);

CREATE TABLE TASKS_GRUPO_ENLACE (
  ID INTEGER,
  TYPE VARCHAR(2),
  CREATOR INTEGER,
  TITLE VARCHAR(30),
  DESCRIPTION  VARCHAR(1000),
  PRIMARY KEY(ID)
);

CREATE TABLE TASKS_USUARIOS (
ID_TAREA INTEGER,
ID_USUARIO INTEGER,
PRIMARY KEY(ID_TAREA,ID_USUARIO)
);