CREATE TABLE USERS_GRUPO_ENLACE (
  ID         INTEGER PRIMARY KEY,
  TYPE VARCHAR(2),
  NAME VARCHAR(30),
  EMAIL  VARCHAR(100)
);

CREATE TABLE TASKS_GRUPO_ENLACE (
  ID         INTEGER PRIMARY KEY,
  TYPE VARCHAR(2),
  CREATOR INTEGER,
  TITLE VARCHAR(30),
  DESCRIPTION  VARCHAR(1000)
);